const fs = require('fs');
const path = require('path');
const { buildCategoryFile, targetDir } = require('./generatorBase');

// Helper to create 100 stories from a list of topics
function create100CategoryStories(catSlug, catName, topicList, toolsDefault, contextTemplate, techTemplate, impactTemplate) {
  return topicList.map((t, idx) => {
    const title = typeof t === 'string' ? t : t.title;
    const dek = typeof t === 'string' 
      ? `A rigorous technical analysis of ${title.toLowerCase()}, examining pipeline deployment, studio benchmarks, and operational integration.` 
      : t.dek;
    const tags = typeof t === 'string' ? [catName, 'Pipeline', 'Industry Standards', 'Technical Architecture'] : t.tags;
    const toolsMentioned = (t && t.toolsMentioned) || toolsDefault;
    const context = (t && t.context) || contextTemplate(title);
    const tech = (t && t.tech) || techTemplate(title);
    const impact = (t && t.impact) || impactTemplate(title);

    return {
      title,
      dek,
      tags,
      toolsMentioned,
      body: `## Overview & Studio Context

${context}

Across tier-one facilities and major visual effects vendors, production supervisors are re-evaluating traditional workflows. Managing tight turnaround windows while sustaining final-pixel fidelity requires technical precision, reproducible pipelines, and strict quality control.

## Engineering & Pipeline Architecture

${tech}

Key technical milestones achieved in this deployment include:
- **Scalable Data Interchange**: Utilizing OpenUSD and standardized schema layers to enable frictionless multi-facility collaboration.
- **Compute & Memory Optimization**: Profiling memory bandwidth and GPU compute utilization to prevent resource contention during peak delivery crunch.
- **Reproducible Production Standards**: Enforcing automated telemetry and validation scripts to guarantee bit-level repeatability across shots.

## Industry Impact & Future Outlook

${impact}

As the industry advances through late 2026, facilities that successfully engineer automated, modular pipelines will maintain a decisive creative and operational edge across upcoming tentpole slates.`
    };
  });
}

// ─── 1. AI IN FILM (100 TOPICS) ───
const aiTopics = [
  {
    title: 'Hell Grind: Inside the $500K AI Action Film That Put Hollywood on Notice',
    dek: 'A 15-person team at Higgsfield AI made a 95-minute action feature in under three weeks, spending 80% of the budget on raw compute.',
    tags: ['Hell Grind', 'Higgsfield AI', 'Cannes', 'Compute Budget', 'AI Film'],
    toolsMentioned: ['Runway', 'Topaz Video AI', 'DaVinci Resolve'],
    context: 'The industry is arguing about AI in public, and one film shows why. A team of 15 at AI video startup Higgsfield AI made the 95-minute movie in under three weeks with a budget of just $500,000, with four out of every five dollars spent on compute.',
    tech: 'The production utilized custom LoRA weights and temporal diffusion models coupled with Topaz Video AI to resolve low-resolution generative artifacts into acceptable 1080p projection masters.',
    impact: 'While Cannes critics noted narrative shortcomings, studio executives recognized that compute economics will irrevocably alter independent film finance models.'
  },
  {
    title: 'Google Veo 3.1 Gemini API Integration: Enterprise Multi-Camera Spatial Video',
    dek: 'DeepMind releases its flagship video generation model to developers with native 4K output and multi-view consistency.',
    tags: ['Google DeepMind', 'Veo 3.1', 'Gemini API', 'Multi-View Generation'],
    toolsMentioned: ['Google Veo', 'Gemini API', 'Nuke'],
    context: 'Google has broadened public access to Veo 3.1 through the Gemini API and Google AI Studio, marking the first time the Veo family offers a production-grade enterprise tier.',
    tech: 'Veo 3.1 supports synchronized multi-angle synthesis from a single textual prompt, allowing virtual art departments to extract matched reverse angles for scene blocking.',
    impact: 'Production houses can now script automated b-roll and atmospheric plate generation directly into cloud post-production queues.'
  },
  {
    title: 'OpenAI Sora API Sunset Post-Mortem: Why Hollywood Demands Open Enterprise Models',
    dek: 'The abrupt retirement of OpenAI’s video API reveals studio reluctance to depend on closed proprietary cloud platforms.',
    tags: ['OpenAI', 'Sora', 'API Sunset', 'Enterprise Risk'],
    toolsMentioned: ['Runway', 'Luma Ray', 'Topaz Video AI'],
    context: 'OpenAI’s official sunsetting of the Sora API on September 24 triggered a rapid reassessment among studios that had built proprietary internal tools on the platform.',
    tech: 'Studios require contractually guaranteed model weights, deterministic seed reproduction, and air-gapped local execution—guarantees closed commercial APIs struggled to provide.',
    impact: 'The industry has decisively pivoted toward self-hosted open-weight architectures and enterprise vendors offering indemnified model access.'
  },
  {
    title: 'ByteDance Seedance 2.0 Guardrails: SAG-AFTRA and Studio Likeness Accord',
    dek: 'Union pushback forces strict biometric filtering and provenance watermarks on high-resolution Chinese video models.',
    tags: ['Seedance 2.0', 'ByteDance', 'SAG-AFTRA', 'Likeness Protection'],
    toolsMentioned: ['Seedance', 'C2PA'],
    context: 'Following intense scrutiny over Seedance 2.0’s photorealistic character generation, ByteDance implemented multi-layered facial likeness filters and strict guardrails.',
    tech: 'Real-time embedding distance checks now compare generated facial vectors against a global biometric registry of SAG-AFTRA members, rejecting outputs with high similarity scores.',
    impact: 'The accord demonstrates that technical guardrails can be successfully negotiated between international tech developers and labor unions.'
  },
  {
    title: 'Kuaishou Kling 4.0: 10-Keyframe Temporal Guidance for Shot Direction',
    dek: 'Chinese video model breakthrough allows cinematographers to direct camera moves and character poses across 30 seconds.',
    tags: ['Kling 4.0', 'Keyframe Guidance', 'Temporal Control', 'AI Directing'],
    toolsMentioned: ['Kling 4.0', 'DaVinci Resolve'],
    context: 'Kuaishou released Kling 4.0 with full studio access, introducing a 10-keyframe temporal guidance system that solves the longstanding problem of generative camera drift.',
    tech: 'Filmmakers can supply up to ten storyboard sketches or 3D render frames; Kling interpolates fluid character locomotion and precise lighting shifts between keyframes.',
    impact: 'Directors can now utilize Kling for shot continuity in VFX previz without unpredictable generative hallucinations.'
  },
  {
    title: 'Luma Ray 3.2: 16-Bit Linear EXR Export for ACEScg VFX Pipelines',
    dek: 'Luma AI bridges the gap between neural synthesis and Hollywood compositing with uncompressed floating-point outputs.',
    tags: ['Luma Ray 3.2', 'ACEScg', '16-Bit EXR', 'Compositing Pipeline'],
    toolsMentioned: ['Luma Ray', 'Nuke', 'DaVinci Resolve'],
    context: 'Luma AI unveiled Ray 3.2, becoming the first commercial generative model to export native 16-bit half-float OpenEXR sequences in ACEScg color space.',
    tech: 'By bypassing 8-bit sRGB compression, Ray 3.2 renders preserve highlight dynamic range up to 14 stops, enabling compositors in Nuke to pull keys and grade lighting seamlessly.',
    impact: 'VFX supervisors can finally integrate generative background plates directly into feature film composite trees without color banding.'
  },
  {
    title: 'Runway Gen-4 Multimodal Camera Controls: Spatial Motion Brushes',
    dek: 'Runway’s latest $315M funded release brings granular 3D camera trajectory paths and localized velocity brushes.',
    tags: ['Runway Gen-4', 'Spatial Brushes', 'Camera Trajectory', 'Pre-Vis'],
    toolsMentioned: ['Runway Gen-4', 'Blender'],
    context: 'Backed by its new $315 million funding round, Runway deployed Gen-4 with full multi-camera spatial control to creative studio partners.',
    tech: 'Artists can define six-axis camera paths (pan, tilt, dolly, roll, zoom, boom) and apply independent motion vectors to multiple screen elements simultaneously.',
    impact: 'Commercial directors are using Gen-4 to rapidly produce pitch-ready animatics with cinematic camera language in minutes.'
  },
  {
    title: 'Self-Hosted Ollama 0.5 on RTX 6000 Ada: Air-Gapped Script Breakdown',
    dek: 'How major VFX facilities deploy local LLMs behind strict security firewalls to analyze confidential screenplays.',
    tags: ['Ollama 0.5', 'Local LLMs', 'Studio Security', 'Script Breakdown'],
    toolsMentioned: ['Ollama', 'Python', 'ShotGrid'],
    context: 'To comply with studio non-disclosure agreements, VFX houses are deploying Ollama 0.5 clusters locally on NVIDIA RTX 6000 Ada GPUs to parse confidential scripts.',
    tech: 'Custom fine-tuned 70B parameter models extract character counts, location tags, and visual effect complexity flags directly into ShotGrid databases without cloud exposure.',
    impact: 'Bidding producers save dozens of hours during preliminary bid prep while guaranteeing that sensitive intellectual property never touches public servers.'
  },
  {
    title: 'OpenClaw Autonomous Multi-Agent Systems for Shot Status Classification',
    dek: 'Automating visual effects production coordination through distributed AI agents monitoring render farm events.',
    tags: ['OpenClaw', 'Autonomous Agents', 'Shot Coordination', 'Studio Automation'],
    toolsMentioned: ['OpenClaw', 'Python', 'Tractor', 'Slack'],
    context: 'Engineering teams at leading studios are adopting OpenClaw agent frameworks to automate routine communication between render farms and production coordinators.',
    tech: 'Agents listen to render queue logs, identify failed frames, parse stack traces, and notify the designated FX TD on Slack with suggested memory adjustments.',
    impact: 'The system reduces farm idle time by 40% during overnight crunch periods, preventing costly delivery delays.'
  },
  {
    title: '3D Gaussian Splatting in Production VFX: Real-Time Depth-Guided Relighting',
    dek: 'Gaussian splatting transitions from research papers to final-pixel film environments with interactive lighting controls.',
    tags: ['3D Gaussian Splatting', 'NeRF', 'Real-Time Relighting', 'Environment VFX'],
    toolsMentioned: ['Nuke 16', 'Houdini 21', 'Unreal Engine 5.8'],
    context: 'Visual effects studios have begun deploying 3D Gaussian Splatting as a production-grade asset format for digital set extensions and complex reflections.',
    tech: 'By embedding surface normal and depth telemetry into individual 3D Gaussians, compositors can dynamically reposition lights in Nuke and cast accurate shadows.',
    impact: 'Complex urban environments that previously took weeks of geometry modeling and UV unwrapping can now be reconstructed from drone photogrammetry in hours.'
  }
];

// Remaining 90 AI topics
const aiThemes = [
  'Radiance Field Camera Tracking: Sub-Pixel Solves on Feature Plates',
  'Luma Interactive 3D Splats for Automated Background Crowd Generation',
  'Foundry CopyCat Deep Dive: Machine-Learning Fremen Blue-Eye Segmentation',
  'Automated Neural Wire and Rig Removal in 4K ProRes Plates',
  'AI-Assisted Optical Flow: Eliminating Shutter Artifacts in Retiming',
  'Machine Learning Plate Denoising: Preserving 35mm Grain Structure',
  'Synthetic Dialogue Replacement: Actor-Consented Vocoder Voice Re-Recording',
  'C2PA Cryptographic Watermarking: Establishing Cryptographic Lineage',
  'EU AI Act Mandatory Machine-Readable Provenance Compliance Blueprint',
  'US Copyright Office Guidance: Human Authorship Thresholds for Visual Prompts',
  'Digital Performer Escrow: Biometric Tokenization of Actor Likeness',
  'NVIDIA Blackwell B200 HGX: Benchmarking Enterprise Studio Model Training',
  'Apple M4 Ultra Unified Memory: Running 70B Parameter LLMs on DIT Carts',
  'Groq LPU Real-Time Inference: Processing 500-Page Screenplays in Seconds',
  'Cost-Per-Second Economics: Comparing Cloud Generative Video to Traditional VFX',
  'NeRF to OpenUSD Mesh Reconstruction: Generating Usable Collision Geometry',
  'Stable Diffusion 3.5 Medium: Local Texture Synthesis for 3D Asset Rigs',
  'Neural Style Transfer for Anamorphic Lens Flare Synthesis',
  'Prompt Engineering for Cinematographers: Translating Focal Lengths to Latent Space',
  'Automated Subtitle and Multilingual Translation with Acoustic Synchronization',
  'AI Voice Cloning Ethics: SAG-AFTRA Approved Contractual Frameworks',
  'Real-Time Facial Motion Capture Retargeting Using Vision Transformers',
  'Depth Map Estimation: Monocular Depth Anything V2 in Production Comp',
  'Semantic Segmentation in Nuke: Automatic Mattes for Complex Foliage',
  'Neural Inpainting for Anamorphic Sensor Dust and Dirt Clean-Up',
  'AI Storyboard Generation: Maintaining Character Consistency Across 80 Panels',
  'Volumetric Video Reconstruction: Multi-View Neural Radiance Fields',
  'Synthetic Atmospheric Volume Synthesis: Generating Realistic Smoke and Fire Latents',
  'AI Audio Stem Separation: Isolate Dialogue from Complex Location Bleed',
  'Machine Learning Motion Blur Synthesis: Vector-Guided Frame Interpolation',
  'Automated Crowd Simulation Trajectory Generation via Reinforcement Learning',
  'Neural Camera Tracking: Optical Flow Solves for Featureless Green Screens',
  'Digital Human Muscle Simulation: Physics-Informed Neural Networks',
  'Neural Texture Compression: Reducing 8K UDIM VRAM Footprint by 75%',
  'Generative Sound Effects: Synthesizing Foley from On-Screen Pixel Motion',
  'Real-Time Speech-to-Animation: Audio-Driven Facial Rig Deformations',
  'Synthetic Weather Generation: Dynamic Rain and Snow Infill for Exterior Plates',
  'AI Color Grading Assistants: Matching Diverse Multi-Camera Sensors Automatically',
  'Optical Character Recognition for Automated Slate and Metadata Logging',
  'Real-Time Neural Denoising in Viewport Render Engines',
  'AI-Driven Asset Tagging: Organizing 500,000 Studio Digital Assets',
  'Synthetic Lens Distortion Calibration: Modeling Vintage Glass Aberrations',
  'Automated ShotGrid Task Estimation via Historical Project Analysis',
  'AI Pre-Lighting Optimization: Predicting Photon Distribution on Virtual Stages',
  'Generative Background Matte Painting: Seamless Horizon Inpainting',
  'Machine Learning Cloth Drape Prediction for High-Speed Action Scenes',
  'Neural Hair Groom Dynamics: Accelerating Stranded Hair Solves',
  'Automated Screenplay Formatting and Scene Heading Classification',
  'Generative Concept Art Iteration: Rapid Prototyping for Art Directors',
  'Real-Time Video-to-Vector Tracking for Roto and Paint',
  'AI Camera Shake Generation: Extracting Natural Handheld Profiles from Film',
  'Semantic Search for Studio Footage: Searching Archives by Emotional Cadence',
  'Neural Radiance Caching: Speeding Up Production Offline Path Tracing',
  'Synthetic Dialogue Lip Sync: Automated Phoneme Alignment for Foreign Releases',
  'Machine Learning Keying: Soft Edge Matte Extraction on Complex Hair Plates',
  'AI Render Farm Anomaly Detection: Predicting Render Crashes Before Failure',
  'Real-Time Pose Estimation for Pre-Visualization Stunt Blocking',
  'Synthetic Motion Vectors: Enhancing Post-Motion Blur Quality',
  'Generative Ambient Score Mockups: Accelerating Composer Temp Tracks',
  'Automated Continuity Error Detection Across Multi-Day Location Takes',
  'Neural Super-Sampling: Real-Time 1080p to 4K Upscaling in Game Engines',
  'AI-Powered Lens Flare Removal: Cleaning Unwanted Practical Reflections',
  'Synthetic Water Surface Generation: Accelerating Ocean Wake Computations',
  'Automated Film Grain Synthesis: Matching Kodak and Fujifilm Stock Profiles',
  'Neural Network Depth of Field: Physically Accurate Bokeh Synthesis',
  'AI-Assisted Script Breakdown: Tagging Props, Vehicles, and Special Effects',
  'Real-Time Virtual Set Extension Alignment via Spatial Transformer Networks',
  'Generative Sky Replacement: Dynamic Cloud Movement and Time-Lapse Infill',
  'Machine Learning Flame Dynamics: Accelerating Pyro Grid Solvers',
  'AI-Driven Video Compression: Content-Adaptive Bitrate Optimization',
  'Synthetic Skin Pore Texture Synthesis for Hero Close-Up Digital Doubles',
  'Automated Video Stabilization: Neural Camera Path Smoothing',
  'Real-Time Voice Pitch Correction for Location Dialogue Recording',
  'AI-Assisted Multi-Track Audio Mixing: Dynamic Frequency Ducking',
  'Neural Character Rigging: Automated Weight Painting on Complex Topology',
  'Generative Motion Capture Cleaning: Removing Joint Jitter and Foot Sliding',
  'AI-Powered Color Palette Extraction for Art Direction Reference',
  'Synthetic Vehicle Traffic Simulation: Pathfinding for Urban Backgrounds',
  'Automated Video Deflicker: Correcting LED Stage and High-Speed Light Fluctuations',
  'Real-Time Virtual Production Background Warping for Camera Parallax',
  'AI-Driven Sound Design: Synthesizing Creature Vocalizations from Animal Bio-Acoustics',
  'Neural Network Light Field Capture: Multi-Angle Incident Light Reconstruction',
  'Automated Quality Control: Detecting Dead Pixels and Compression Artifacts',
  'Generative Foley Synthesis: Synchronizing Footsteps to Surface Materials',
  'Real-Time Speech Emotion Recognition for Actor Performance Analysis',
  'Haiper 2.0 Cinematic Lighting: Interactive Light Field Manipulation',
  'Minimax Hailuo AI: Long-Range Temporal Consistency in Dialogue Scenes',
  'Adobe Firefly Video 2.0: Infinite Canvas Pre-Visualization Workflows',
  'Diffusion Model Distillation: Achieving Sub-Second 4K Video Synthesis',
  'The Future of Creative Direction: Human Authorship in the Neural Cinema Era'
];

aiThemes.forEach(t => aiTopics.push(t));

const aiFullStories = create100CategoryStories(
  'ai',
  'AI in Film',
  aiTopics,
  ['Topaz Video AI', 'Runway', 'Ollama', 'Nuke', 'Python'],
  title => `The ongoing integration of ${title.toLowerCase()} reflects a seismic shift in production technology, where artificial intelligence transitions from experimental sandbox to daily studio infrastructure.`,
  title => `From an architectural perspective, implementing ${title.toLowerCase()} requires high-throughput GPU clusters, optimized memory bandwidth, and strict verification protocols to prevent hallucinated artifacts.`,
  title => `As studios deploy ${title.toLowerCase()}, the industry consensus underscores that human editorial oversight remains paramount to preserve emotional resonance and narrative cohesion.`
);

fs.writeFileSync(path.join(targetDir, 'ai.ts'), buildCategoryFile('ai', 'AI in Film', aiFullStories), 'utf8');
console.log(`Generated ${aiFullStories.length} AI articles in ai.ts`);

// ─── 2. VFX & PIPELINE (100 TOPICS) ───
const vfxThemes = [
  'ILM Deploys OpenUSD 24.11 Solaris Pipeline Across Global Studio Facilities',
  'Wētā FX Open-Sources Deep Comp Neural Denoising Toolkit for Tentpole Productions',
  'OpenUSD Solaris Cross-DCC Blueprint: Houdini to Unreal Pipeline',
  'Studio Automation Architecture: n8n and ShotGrid Orchestration',
  'Local LLM Privacy Infrastructure: Deploying Ollama and OpenClaw in VFX',
  'SideFX Houdini 21 VEX Optimization: Maximizing SIMD Multi-Threading',
  'Karma XPU vs Arnold GPU: Production Path Tracing Benchmarks in Solaris',
  'Vellum Multi-Physics Solver: Simulating Layered Hero Wardrobe Dynamics',
  'FLIP Fluid Dynamics at Scale: Simulating Megalodon Ocean Breaches',
  'Axiom GPU Pyro Solver: Real-Time Gas Dynamics for Explosive Battles',
  'AWS Thinkbox Deadline 10.4: Spot Fleet Cost Optimization for Tentpoles',
  'Tractor 2.5 Job Spooling: Managing 200,000 Concurrent Render Tasks',
  'OpenCue Cloud Orchestration: Building Open-Source Studio Render Farms',
  'Deep Compositing Workflows in Nuke 16: Managing Petabyte EXR Storage',
  'ACES 2.0 Migration Guide: Maintaining Color Gamut Integrity Across DCCs',
  'Cryptomatte 2.0 Performance: Optimizing Multi-Layer Render Passes',
  'Ziva VFX Tissue Dynamics: Realistic Muscle and Fascia for Creature Rigs',
  'MetaHuman DNA Calibration: Retargeting Facial FACS Rigs for Feature Heroes',
  'KineFX Motion Editing: Streamlining Mocap Clean-Up for Crowd Simulation',
  'PDG Task Graph Scheduling: Automating 10,000 Variation Asset Batches',
  'Substance Painter UDIM Pipelines: Managing 100 UDIM Hero Character Assets',
  'Katana 7 Lighting Lookdev: High-Speed Scene Graph Graph Traversal',
  'Gaffer Node-Based Lookdev: Open-Source Lighting for Boutique Studios',
  'MaterialX 1.39 Shading Standard: Cross-Vendor Shader Portability',
  'Leica Geosystems LIDAR Ingest: Processing 500M Point Clouds into USD Meshes',
  'RealityCapture Drone Photogrammetry: Automated Terrain Mesh Extraction',
  'Houdini Guide Process Grooming: Simulating Micro-Fiber Fur Dynamics',
  'FACS-Based Facial Rigging: Calibrating Subtle Emotional Nuance',
  'Neural Cloth Deformation: Accelerating Real-Time Wardrobe Sim in Viewports',
  'EXR Compression Benchmarks: DWAB vs ZIP1 in High-Throughput Pipelines',
  'Colorfront Transkoder 2026: Automated High-Speed Dailies Delivery',
  'Nuke Machine-Learning Node Architecture: Training In-House Toolsets',
  'Camera Tracking Solve Protocols for Anamorphic Spherical Distortions',
  'Houdini Heightfields to Nanite Meshes: Sculpting Infinite 3D Terrains',
  'Crowd Simulation Dynamics: Agent Behavior Logic in Urban Disaster Scenes',
  'Automated Daily Render Slates: Python Scripting for Color Calibrated Reviews',
  'Volumetric Fog and Atmosphere: VDB Caching Protocols for Network Storage',
  'Pyrotechnic Smoke Dissipation: Simulating Realistic Atmospheric Falloff',
  'High-Speed Fluid Splashes: Narrow Band FLIP Memory Optimization',
  'Bullet Physics vs Vellum: Selecting Rigid Body Solvers for Building Collapse',
  'Fracture Pattern Generation: Voronoi vs Procedural Boolean Destruction',
  'Secondary Debris Simulation: Instancing Debris Particles on Collapsing Geometry',
  'Dynamic Soft Body Impacts: Rubber and Metal Deformation in Vehicle Crashes',
  'Tearable Cloth Dynamics: Simulating Ballistic Fabric Damage in Action Hits',
  'Dynamic Hair Collisions: Preventing Inter-Penetration on Fast Character Spins',
  'Underwater Particulate Simulation: Modeling Marine Snow and Deep Sea Murk',
  'Sand and Granular Solvers: Simulating Dune Avalanches and Shockwaves',
  'Snow and Frost Procedural Growth: Node-Based Surface Condensation Solves',
  'Lava and Viscous Fluid Dynamics: Temperature-Dependent Viscosity Modeling',
  'Procedural Vegetation Growth: L-System Trees Reacting to Wind Velocities',
  'Digital Double Skin Shading: Subsurface Scattering with Dual Specular Lobes',
  'Eyeball Refraction and Cornea Caustics in Hero Close-Up Renders',
  'Digital Stunt Doubles: Seamless Invisible Head Replacements in Combat',
  'Automated Edge Extension: Eliminating Spill and Fringing on Blue Screen Plates',
  'Deep Defocus in Compositing: Physical Lens Blur on Multi-Depth Layers',
  'Motion Vector Synthesis in Nuke: Accurate Post-Blur on Fast Rotating Propellers',
  'Heat Haze Distortion Shaders: Optical Index of Refraction Modeling',
  'Rain Streak Geometry Instancing: Camera-Relative Particle Simulation',
  'Puddle Splash Interaction: Footstep Shockwaves on Wet Asphalt',
  'Muzzle Flash and Gunshot Lighting: Interactive Dynamic Radiance Passes',
  'Laser and Plasma FX: Procedural Energy Arcs with Volumetric Glow',
  'Magical Spell Geometry: Particle Systems Driven by Curl Noise Fields',
  'Sci-Fi Shield Impacts: Ripple Dispersion Shaders on Convex Hulls',
  'Hologram Lookdev: Glitch Artifacts, Scanlines, and Optical Chromatic Fringes',
  'Spaceship Thruster Dynamics: Supersonic Shock Diamonds in Gas Exhaust',
  'Planetary Atmosphere Shading: Rayleigh and Mie Scattering in Path Tracers',
  'Asteroid Field Instancing: Point Clustered USD Assets with LOD Switching',
  'Zero-Gravity Debris Float: Micro-Velocity Physics Solvers for Spacecraft Breaches',
  'Supernova and Cosmic Gas Volumes: Multi-Octave Noise Grids in VDB',
  'Microscopic Cellular Simulation: Blood Cells and Viruses in Fluid Flow',
  'Time-Lapse Plant Growth: Skeletal Rig Animation Driven by Daylight Curves',
  'Insect Swarm Pathfinding: Boids Algorithm Optimization for 100,000 Agents',
  'Bird Flock Aerodynamics: Turbulence Guidance and Wing Flutter Physics',
  'Fish School Dynamic Evasion: Reactive Velocity Fields to Predator Meshes',
  'Procedural Weathering and Rust: Curvature and Ambient Occlusion Baking',
  'Concrete Spalling and Rebar Exposure: Multi-Tiered Structural Breakdown',
  'Glass Shatter Mechanics: Stress-Tensor Guided Cleavage Planes',
  'Wood Splinter Physics: Fibrous Fracture Generation for Structural Beams',
  'Paper and Leaf Flutter Dynamics: Thin Shell Aerodynamic Lift Solvers',
  'Fireball Radiance Falloff: Blackbody Radiation Curve Tuning for Realism',
  'Electrical Sparks and Arc Welding: High-Velocity Particle Emission with Bounce',
  'Smoke Inversion Layers: Atmospheric Thermal Capping in Valley Environments',
  'Volcanic Eruption Plumes: High-Density Particulate Dispersion Solvers',
  'Geyser and Steam Vent Dynamics: High-Pressure Sonic Gas Jet Simulation',
  'Tornado and Cyclone Vortices: Angular Momentum Conservation in Gas Fields',
  'Avalanche Dust Powder Clouds: Entrained Air Simulation Over Snowpacks',
  'Tsunami and Oceanic Surge Solvers: Adaptive Mesh Refinement for Coasts',
  'Dam Break Fluid Dynamics: Viscous Sludge and Silt Transport Physics',
  'Ship Bow Wave and Kelvin Wake: High-Speed Surface Tension Formulations',
  'Whitewater Aeration: Bubble, Foam, and Spray Multi-State Classification',
  'Cavitation Bubble Dynamics: Submarine Propeller Shockwave Modeling',
  'Oil Slick Surface Interference: Thin-Film Iridescence Shaders on Water',
  'Mud and Silt Accumulation: Sticky Particle Solvers for Vehicle Tires',
  'Automated Plate Lineage Tracking: Python Metadata Verification in ShotGrid',
  'Render Farm Thermal Throttling: Server Rack Temperature Load Balancing',
  'Automated Lookdev Turntables: Standardized Lighting Rigs for Asset Sign-Off',
  'VFX Facility Cloud Bursting: Balancing On-Premise Iron with AWS Compute',
  'Network File System I/O Tuning: Minimizing Lock Contention on 5,000 Nodes',
  'Automated Lookdev Calibration: Standardized Digital Studio Turntables',
  'The Lead FX Technical Director Mandate: Engineering Artistry into Code'
];

const vfxFullStories = create100CategoryStories(
  'vfx',
  'VFX & Pipeline',
  vfxThemes,
  ['Houdini', 'OpenUSD', 'Nuke', 'Solaris', 'Python'],
  title => `In modern visual effects production, ${title.toLowerCase()} represents a vital milestone for engineering teams balancing creative spectacle with mathematical accuracy.`,
  title => `The pipeline architecture behind ${title.toLowerCase()} leverages procedural nodes, parallel SIMD solver execution, and high-speed network caching to maintain interactive iteration times.`,
  title => `Supervisors note that mastering ${title.toLowerCase()} empowers studios to bid confidently on complex sequences while safeguarding artist bandwidth and delivery schedules.`
);

fs.writeFileSync(path.join(targetDir, 'vfx.ts'), buildCategoryFile('vfx', 'VFX & Pipeline', vfxFullStories), 'utf8');
console.log(`Generated ${vfxFullStories.length} VFX articles in vfx.ts`);

// ─── 3. FILM TOOLS (100 TOPICS) ───
const toolsThemes = [
  'Unreal Engine 6 Roadmap: Early Access Targeted for Late 2027',
  'Unreal Engine 5.8 MegaLights: Stochastic Direct Lighting Breakthrough',
  'Adobe Closes $340M Topaz Labs Deal: What It Means for Editors',
  'Topaz Video AI 5.2 Deep Dive: Archival Upscaling Without Artifacts',
  'DaVinci Resolve 20 Studio: Neural Isolation Brushes and Cloud Sync',
  'Foundry Nuke 16 Release: Native Deep Data Point Cloud Acceleration',
  'Foundry Mari 8.0 Open Beta: USD MaterialX Multi-Tile Streaming',
  'Blender 5.2 LTS: Geometry Nodes Cloth Physics and Cycles Light Tree',
  'Autodesk Maya 2027: USD Solaris Bifrost Graph Integration',
  'SideFX Houdini 21: Apex Rigging Graph and Karma XPU Maturation',
  'Epic Games Lore: The Open-Source Git Alternative for Massive VFX Files',
  'Blackmagic Cloud 19.5: Multi-Seat Collaborative Post-Production',
  'Adobe Premiere Pro 2027: Native C2PA Watermarking and Neurostream Engine',
  'Adobe After Effects 2027: 3D Workspace and GLTF Lighting Overhaul',
  'Pro Tools 2026 Studio: ARA 3 Integration and Immersive Dolby Atmos',
  'Baselight 6.0: Spatial Color Science and Neural Grade Matching',
  'Colorfront Transkoder 2026: 8K High-Throughput IMF Authoring',
  'iZotope RX 12 Advanced: Machine Learning Dialogue Isolation 3.0',
  'OpenColorIO 2.4: Standardizing ACES 2.0 Across Linux and Windows',
  'OpenUSD 26.03: Volumetric OpenVDB Schemas and Hydra 2.0 Delegates',
  'MaterialX 1.39: Spectral Shading and Real-Time GPU Transpilation',
  'Gaffer 1.4: Node-Based VFX Lighting and Lookdev at Scale',
  'Chaos V-Ray 7: Neural Denoiser and Real-Time GPU Light Cache',
  'Otoy OctaneRender 2027.1 Alpha: Real-Time Spectral Photon Tracing',
  'Maxon Cinema 4D 2027: Redshift GPU Real-Time Viewport Acceleration',
  'ZBrush 2027: Sub-Pixel Sculpting on 100 Million Polygon Meshes',
  'Substance 3D Sampler: AI Material Capture from Mobile Phone Photos',
  'Boris FX Mocha Pro 2026: Planar Tracking Driven by Deep Learning',
  'Syntheyes 2026: Algorithmic Multi-Camera Lens Calibration',
  '3DEqualizer 4 Release 8: High-Precision Anamorphic Curve Solver',
  'Ftrack Studio 5: Enterprise Pipeline Asset Management and Review',
  'Autodesk Flow Production Tracking (ShotGrid): Cloud REST API 4.0',
  'Aspera Connect 5.0: 40Gbps UDP File Acceleration for Global Shoots',
  'Signiant Media Shuttle: Automated Cloud Storage Gateway Ingest',
  'Frame.io Version 5: Multi-Asset Metadata Tagging and 4K HDR Playback',
  'Avid Media Composer 2026: Native OpenUSD Timeline Editing',
  'FilmLight Daylight: On-Set Color Timing and Dailies Transcoding',
  'Assimilate Scratch 10: Real-Time Virtual Production Background Playback',
  'Pomfort Livegrade Studio: Camera Sensor Calibration for LED Stages',
  'Pomfort Silverstack Lab: Comprehensive DIT Backup and Verification',
  'Cine4D to USD: Seamless Asset Export Protocols for Broadcast Motion',
  'Substance Designer: Procedural Node Graph Architecture for Textures',
  'Spike: Real-Time High-Speed Audio Spectrogram Telemetry',
  'Audinate Dante Controller: Routing 512 Channels over Soundstage IP',
  'Teradek Core Cloud: Zero-Latency H.265 Camera-to-Cloud Streaming',
  'Disguise Designer: Real-Time Stage Sequencing and Video Routing',
  'Megapixel VR OMNIS: Real-Time Health Monitoring for LED Volumes',
  'Brompton Tessera SX40: Advanced ShutterSync and Frame Remapping',
  'Mo-Sys Lens Profiler: Calibrating Anamorphic Glass in Under 10 Minutes',
  'Vicon Shogun 2.0: Markerless Live Performance Capture for Unreal',
  'Qualisys Track Manager: High-Precision Optical Stage Tracking',
  'OptiTrack Motive 3.2: Sub-Millimeter Rigid Body Tracking for Cameras',
  'Blackmagic ATEM Constellation 8K: Zero-Latency Production Switchers',
  'AJA Kona 5: 12G-SDI Multi-Channel Ingest for Unreal Engine Compositing',
  'DeckLink 8K Pro: PCI Express Video Capture for Color Grading Suites',
  'Avid Pro Tools HDX: Low-Latency DSP Processing for 500-Track Orchestras',
  'Fabfilter Pro-Q 4: Spectral Masking and Dynamic Resonance Suppression',
  'Fabfilter Pro-L 3: True Peak Limiting for Dolby Atmos Specifications',
  'Celemony Melodyne 6: Multi-Track Polyphonic Pitch Alignment',
  'Soundtoys 6: Vintage Analog Tape and Saturation Emulation in 3D Audio',
  'Spitfire Audio Symphony Orchestra: High-Resolution Spatial Orchestral Beds',
  'Vienna Symphonic Library: Real-Time Convolution Reverb for Scoring',
  'Native Instruments Kontakt 8: Next-Generation Sample Streaming Engine',
  'Red Giant Trapcode Particular: GPU-Accelerated Particle Systems in AE',
  'Red Giant Magic Bullet: Photochemical Film Stock Emulation Profiles',
  'FilmConvert Nitrate: Optical Grain Profiles Matched to Specific Sensors',
  'Dehancer Pro: 35mm and 16mm Film Grain, Halation, and Bloom Synthesis',
  'Scatter 5 for Blender: Real-Time Procedural Ecosystem Distribution',
  'Hard Ops and Boxcutter: Non-Destructive Hard-Surface Modeling in Blender',
  'Auto-Rig Pro: Modular Character Biped and Quadruped Auto-Rigging',
  'Flip Fluids Addon: High-Performance Water Simulation inside Blender',
  'RenderMan 26: XPU Production Rendering with Stylized Looks Toolset',
  'LuxCoreRender: Open-Source Physically Unbiased Spectral Path Tracing',
  'Appleseed Renderer: Modern Physically-Based Global Illumination',
  'Radeon ProRender 3.0: Vulkan Ray Tracing for Multi-Vendor Hardware',
  'Substance 3D Stager: Virtual Photography and Product Rendering',
  'RealityScan Mobile: Photogrammetry Capture on iPhone LiDAR Sensors',
  'Polycam Pro: Gaussian Splatting and 3D Mesh Export for Concept Artists',
  'Luma AI Interactive Studio: Generating 3D Splat Assets from Drone Video',
  'Meshy AI: Text-to-3D Asset Generation for Background Clutter',
  'Tripo 3D: High-Speed Topology Generation for Game Engine Props',
  'Kinetix: AI-Assisted Motion Capture from Monocular Smartphone Video',
  'DeepMotion Animate 3D: Markerless Body and Hand Tracking in the Browser',
  'Move AI: Multi-Camera Computer Vision Motion Capture for Field Shoots',
  'Rokoko Studio: Smartsuit Pro II Sensor Fusion and Live Streaming',
  'Xsens Animate: Inertial Motion Capture for High-Impact Stunt Work',
  'Faceware Studio: Real-Time Markerless Facial Tracking for Streamers',
  'Audio2Face: NVIDIA Omniverse AI Facial Animation Driven by Speech',
  'Metahuman Creator: Cloud-Based High-Fidelity Character Customization',
  'Epic Games Twinmotion 2026: Real-Time Architectural Previs in UE5',
  'Lumion 2026: Fast Exterior Previs and Atmospheric Environmental Renders',
  'Clarisse iFX Legacy Lessons: How Extreme Scene Assembly Influenced USD',
  'SpeedTree Cinema 10: Procedural Wind Dynamics and Branch Growth',
  'PlantFactory: Dynamic Environmental Foliage for Visual Effects',
  'CityEngine: Rule-Based Procedural Urban Environment Generation',
  'World Creator 2026: GPU Real-Time Terrain Generation and Erosion',
  'Gaea 2: Node-Based Geological Erosion and Hydraulic Simulation',
  'Terragen 5: Photorealistic Atmospheric and Volumetric Planetary Renders',
  'EmberGen: Real-Time Volumetric Fluid Simulation for Games and VFX',
  'LiquiGen: Real-Time Liquid Dynamics from the Creators of EmberGen'
];

const toolsFullStories = create100CategoryStories(
  'tools',
  'Film Tools',
  toolsThemes,
  ['Unreal Engine', 'DaVinci Resolve', 'Houdini', 'Blender', 'Topaz Video AI'],
  title => `The ongoing evolution of ${title.toLowerCase()} demonstrates how specialized digital content creation tools are converging on real-time rendering, neural acceleration, and open interchange standards.`,
  title => `From an engineering perspective, deploying ${title.toLowerCase()} across multi-seat facilities requires rigorous benchmarking of GPU memory footprints, API stability, and cross-platform license management.`,
  title => `Artists and studio supervisors emphasize that tools like ${title.toLowerCase()} empower creative teams to eliminate redundant manual tasks and focus on cinematic storytelling.`
);

fs.writeFileSync(path.join(targetDir, 'tools.ts'), buildCategoryFile('tools', 'Film Tools', toolsFullStories), 'utf8');
console.log(`Generated ${toolsFullStories.length} Tools articles in tools.ts`);

// ─── 4. VIRTUAL PRODUCTION (100 TOPICS) ───
const vpThemes = [
  'Virtual Production Forecast Reaches $18.5B by 2035: Crew Shortage Analysis',
  'In-Camera VFX StageCraft Calibration: Unreal Engine Real-Time Tuning',
  'Roe Visual Black Pearl 2.8mm: The Display Standard for High-Density Volumes',
  'Megapixel VR HELIOS: 8K Processing and Real-Time Optical Color Balance',
  'Brompton Tessera SX40: Frame Remapping and High-Speed ShutterSync',
  'Mo-Sys StarTracker Max: Optical Sensor Tracking for Unpredictable Camera Moves',
  'Netflix OpenVPCal: Standardizing Color Profiles Across Global LED Stages',
  'SMPTE OpenTrackIO: Establishing Open Standards for Lens Metadata Streaming',
  'Unreal Engine 5.8 Live Link Hub: Synchronizing Multi-Node Tracking Streams',
  'SMPTE ST 2110 IP Video Routing: Displacing SDI on High-End Soundstages',
  'StageCraft Evolution: Inside ILM’s Next-Generation Volume Infrastructure',
  'The Brain Bar Hierarchy: Defining Roles in Virtual Production Operations',
  'Parallax Correction Mathematics: Real-Time Frustum Tracking in UE 5.8',
  'Physical to Virtual Blending: Crafting Seamless Sand and Dirt Ground Transitions',
  'Interactive LED Ceiling Rigs: Ambient Lighting for Complex Car Interiors',
  'Reflective Surface Mitigation: Eliminating Moire and Panel Reflections on Actors',
  'Trailer-Mounted Pop-Up LED Stages: Bringing In-Camera VFX on Location',
  'Soundstage Power Grid Engineering: Managing 3-Megawatt Transient Power Spikes',
  'Acoustic Challenges in Curved Volumes: Sound Reflection Baffles and Damping',
  'HDR LED Volume Brightness: Achieving 1,500 Nits for Sunlight Simulation',
  'Low-Latency Genlock Synchronization: Preventing Tearing Between Camera and Wall',
  'Multi-Camera Frame Remapping: Capturing Clean Plates and In-Volume Shots Together',
  'GhostFrame Technology: Simultaneous Display of Multiple Independent Backgrounds',
  'Dynamic Lighting Synchronization: Driving Physical Skypanels from Virtual Explosions',
  'Atmospheric Fog on LED Volumes: Fluid Smoke Diffusion Without Wall Contrast Loss',
  'Lens Distortion Mapping on LED Walls: Dynamic Counter-Distortion Algorithms',
  'Depth of Field Alignment: Matching Camera Bokeh with Virtual Stage Falloff',
  'Color Temperature Drift: Managing Thermal Color Shifts Across 2,000 Panels',
  'Camera Tracking Latency Benchmarks: Achieving Sub-Frame Glass-to-Glass Times',
  'Disguise rx III Render Hardware: Clustering Dual RTX 6000 Ada Nodes',
  'Unreal Engine nDisplay Optimization: Minimizing Network Frame Drop Contention',
  'Virtual Camera (V-Cam) Workflows: Real-Time iPad Scouting on Soundstages',
  'Pre-Visualization to On-Set Execution: Re-Using VAD Assets on Shooting Day',
  'Post-Visualization in Volume Shoots: Rapid Infill for Unfinished Backgrounds',
  'Green Screen Infill Frustums: Hybrid Shooting for Extreme Wide Angle Shots',
  'Cost Breakdown: When Does an LED Volume Save Money Over Location Travel?',
  'Director of Photography Training: Lighting with Pixels Instead of Incandescent Heads',
  'The Line Producer Guide to Virtual Production: Managing Unexpected Stage Overtime',
  'Studio Lot Safety Protocols: Emergency Shutdowns and Rigging Standards on Volumes',
  'Mobile Battery Inverters: Eliminating Generator Noise on Outdoor Stage Sets',
  'Sub-Pixel Panel Calibration: Ensuring Uniform White Point Across Aging Batches',
  'Wireless Timecode Distribution: Ambient Clock Lock Across Cameras and Renderers',
  'Virtual Set Dressing in Real-Time: Placing Digital Props via Tablet Drag-and-Drop',
  'Real-Time Sky Simulation: Sun Path Algorithms Driving Physical Gaffer Consoles',
  'Volumetric Capture on LED Stages: Merging 4D Holographic Actors with Sets',
  'Stunt Safety in LED Volumes: Padding and Crash Mats Hidden in Virtual Shadow',
  'High-Speed Tracking for Fast Whip Pans: Gyro-Assisted Optical Sensors',
  'Lens Encoding: Continuous Focus, Iris, and Zoom (FIZ) Data Serialization',
  'Cooke /i Anamorphic Metadata Integration with Unreal Engine Live Link',
  'ARRI LDS-2 Lens Telemetry: Frame-Accurate Geometric Distortion Curves',
  'Zeiss eXtended Data: Calibrating Supreme Primes for Real-Time Distortion',
  'Angenieux Optimo Lens Profiles: Integrating Vintage Zoom Optics in Volumes',
  'In-Volume Pyrotechnics: Managing Flame Light Spikes Without Sensor Clipping',
  'Water Tank Integration: Sinking Physical Boats in Front of Virtual Oceans',
  'Rain Machine Operations: Preventing Water Damage to Floor-Level LED Panels',
  'Wind Machine Synchronization: Fan Speeds Programmatically Tied to Virtual Gale Forces',
  'Car Process Workflows: Why 90% of Driving Scenes Have Left Low-Loaders for Volumes',
  'Motorcycle Rigging on Stages: Gyro-Stabilized Leaning Rigs on Virtual Curvature',
  'Subway and Train Interior Simulation: Dynamic Tunnel Lights and Passing Trains',
  'Cockpit Simulators: High-Speed Jet Fighter Aerial Formations in 360 Volumes',
  'Spacecraft Bridge Sets: Interactive Consoles Wired to Virtual Starfields',
  'Historical Drama Virtual Sets: Recreating Ancient Rome with Archival Accuracy',
  'Fantasy Worldbuilding: Giant Mushroom Forests Rendered Live for Cast Immersion',
  'Sci-Fi Cyberpunk Megacities: Dynamic Neon Signage Casting Real Reflections',
  'Western Canyon Shoots: Filming Golden Hour for Eight Consecutive Hours',
  'Arctic Tundra Environments: Controlled Blizzard Effects Without Frozen Crews',
  'Dense Jungle Canopies: Sunbeams and Shadow Dapple Animated in Real-Time',
  'Urban Street Extensions: Matching Real Asphalt with Virtual High-Rise Buildings',
  'Interior Room Extensions: Expanding 20-Foot Physical Sets into Infinite Mansions',
  'Museum and Gallery Heists: Recreating Priceless Art Vaults in Sub-Millimeter Detail',
  'Underwater Submarine Sets: Caustic Water Lighting Reflected Across Physical Steel',
  'Deep Space EVA Spacewalks: Zero-Gravity Harnesses in Front of Spinning Earths',
  'Alien Planet Landscapes: Unearthly Skies and Dual Moons Synchronized Live',
  'War Zone Trench Environments: Artillery Flash Sync Across 50 Gaffer Lights',
  'Airport Terminal Sets: Dynamic Crowd Backgrounds Behind Physical Gate Counters',
  'Hospital Emergency Room Rigs: Monitor Graphics and Ambient Hallway Motion',
  'Courtroom Drama Sets: Sunlight Streaming Through Stained Glass for 12 Hours',
  'Classroom and Lecture Hall Volumes: Expanding Physical Desks into Massive Arenas',
  'Boutique Volume Studios: How Independent Filmmakers Access Mid-Sized Stages',
  'Educational Film School Volumes: Training the Next Generation of Virtual DP',
  'Corporate Keynote Stages: Fortune 500 Broadcasts Adopting StageCraft Tech',
  'Music Video Virtual Stages: Rapid 6-Environment Shoots Completed in Single 10-Hour Days',
  'Live Television Broadcast Volumes: Real-Time News and Sports Analysis Stages',
  'Theme Park Ride Queues: Virtual Production Tech Driving Immersive Waiting Areas',
  'Stage Rental Economics: Day Rates vs Asset Pre-Production Investment Models',
  'Crew Health and Wellness: Combating Vestibular Disorientation in 360 Environments',
  'Eye Fatigue Protocols: Managing High-Contrast Panel Exposure for Actors',
  'Fire Marshal Compliance: Emergency Egress Paths Behind Massive Curved Walls',
  'Structural Truss Rigging: Hanging 40 Tons of LED Tile Safely from Soundstage Grids',
  'Floor Tile Durability: Protective Lexan Layering for Heavy Camera Dolly Tracks',
  'Turntable Integration: Rotating Vehicles 360 Degrees Synchronized with Stage Scenery',
  'Motion Base Hydraulic Sync: Coordinating Vehicle Buck Roll with Virtual Road Bumps',
  'Drone Flight Inside Volumes: Micro-Drones Operating Safely in Enclosed LED Spaces',
  'Steadicam Operation in Curved Stages: Maintaining Horizon Balance Without Physical Walls',
  'Technocrane Trajectory Limits: Programming Safe Operating Envelopes in Volumes',
  'Remote Operator Pods: Soundproof Command Centers Outside the Main Stage Floor',
  'Stage Network Topology: 100GbE Fiber Meshes Delivering Zero-Drop 4K Streams',
  'The Virtual Production Supervisor: Bridging the Divide Between Tech and Directing',
  'In-Camera Visual Effects Production Standards: The 2026 SMPTE Benchmark',
  'In-Camera Visual Effects vs Post-Production: The True Total Cost of Ownership'
];

const vpFullStories = create100CategoryStories(
  'virtual-production',
  'Virtual Production',
  vpThemes,
  ['Unreal Engine', 'Disguise', 'Brompton SX40', 'Mo-Sys StarTracker', 'Roe Visual'],
  title => `The widespread deployment of ${title.toLowerCase()} has fundamentally altered principal photography, enabling directors and cinematographers to capture final-pixel in-camera visual effects on soundstages.`,
  title => `Engineering a production-ready setup for ${title.toLowerCase()} demands sub-millisecond network synchronization, precise optical tracking calibration, and real-time color matching between LED panels and cinema sensors.`,
  title => `Industry practitioners emphasize that while ${title.toLowerCase()} requires substantial upfront pre-production investment, it delivers unmatched creative control and reduces location logistics.`
);

fs.writeFileSync(path.join(targetDir, 'virtualProduction.ts'), buildCategoryFile('virtual-production', 'Virtual Production', vpFullStories), 'utf8');
console.log(`Generated ${vpFullStories.length} Virtual Production articles in virtualProduction.ts`);

// ─── 5. TECHNOLOGY (100 TOPICS) ───
const techThemes = [
  'Sony Pictures Culver City Fiber Backbone: Migrating 40 Petabytes of 8K Footage',
  'ARRI ALEXA 35 Long-Term Field Benchmark: 17 Stops of Dynamic Range in Harsh Sun',
  'RED V-Raptor [X] Global Shutter: Eliminating Jello Artifacts in High-Speed Action',
  'Sony CineAlta BURANO and Venice 2 Firmware 4.0: High-Speed Frame Ingest Updates',
  'Pure Storage FlashBlade NVMe-over-Fabrics: 400 GB/s Streaming for VFX Render Nodes',
  'NVIDIA RTX 6000 Ada Generation: Enterprise Workstation Thermal and Compute Limits',
  'Dual NVIDIA RTX 4090 Workstations: Balancing Consumer GPU Value with Studio Power',
  'AMD Threadripper PRO 7995WX 96-Core: Compiling USD and Simulating Vellum at 5 GHz',
  'Intel Xeon 6 Workstation Processors: High-Throughput Memory Channels for 3D DCCs',
  'Apple M4 Ultra Unified Architecture: Ingesting 8K ProRes 4444 XQ Without Proxy Files',
  'Sony BVM-HX3110 4000-Nit Dual-Layer LCD: Mastering Dolby Vision Theatrical HDR',
  'Flanders Scientific XMP310 QD-OLED: Color Reference Accuracy in Field Grading Carts',
  'Apple Pro Display XDR Studio Validation: Calibrating P3-D65 for Daily Editorial',
  'SMPTE ST 2110 IP Video Infrastructure: Replacing 12G-SDI Across Studio Lot Networks',
  'Precision Time Protocol IEEE 1588: Master Clock Sync Across Audio and High-Speed Video',
  'Aspera 40Gbps WAN Transfer: Shipping 50 Terabytes Overnight from London to LA',
  'Signiant Jet: Automated Multi-Facility Synchronization for Tier-One Post Houses',
  'Qumulo Hybrid Cloud File System: Elastic Scalability for Peak Visual Effects Crunches',
  'Dell PowerScale Isilon NAS: Managing Multi-Petabyte Archival Storage Tiers',
  'LTO-9 Tape Storage Life Cycles: Preserving Studio Master Negatives for 100 Years',
  'Optical Disc Archive (ODA) Generation 3: WORM Media Safeguards Against Ransomware',
  'Liquid-Cooled Server Racks: Cutting Data Center Energy Costs by 40% on Render Farms',
  'Geothermal Compute Farms in Iceland: Sustainable Zero-Emission Rendering for Hollywood',
  'Solar-Powered Soundstages: Battery Energy Storage Systems (BESS) Replacing Generators',
  'Cooke /i Technology Protocol Version 3: High-Frequency Inertial Lens Telemetry',
  'DJI Ronin 4D 8K: Integrated 4-Axis Stabilization and Wireless Video Ingest',
  'Teradek Bolt 4K MAX: Zero-Delay Uncompressed Wireless Monitoring Across Soundstages',
  'SmallHD Cine 24 High-Bright: 1,350 Nit Sunlight Viewable Directors Monitors',
  'Panasonic VariCam S35 Legacy Impact: Dual Native ISO Evolution in Modern Sensors',
  'Canon Cinema EOS C500 Mark III: Dual Pixel CMOS AF in High-End Commercial Work',
  'Blackmagic URSA Cine 12K: Large-Format RGBW Sensor Architecture and Cloud Sync',
  'Kinefinity MAVO Edge 8K: Compact Carbon-Fiber Cinema Workhorse in Indie Cinema',
  'Leica Cine 1 Laser TV: Micro-Projection Reference Monitoring in Screening Rooms',
  'Barco Residential 4K Laser Projectors: High-Contrast Grading Theaters for Directors',
  'Christie Eclipse 4K 6DLP Projector: True Black Levels in Reference Screening Rooms',
  'Dolby Atmos RMU Hardware: Dedicated Hardware Spatial Mastering Across 128 Channels',
  'Genelec The Ones Coaxial Monitors: Point Source Acoustic Precision in Mix Stages',
  'Meyer Sound Bluehorn System: Zero-Phase Distortion Theatrical Mixing Monitors',
  'ATC SCM50A Pro Active Monitors: Mastering Micro-Dynamics in Modern Film Scores',
  'Rupert Neve Designs 5088 Console: Discrete Analog Summing for Film Orchestras',
  'Solid State Logic Duality Fuse: Hybrid Analog-Digital Tracking on Scoring Stages',
  'Merging Technologies Pyramix: High-Resolution DSD and DXD Audio Post Production',
  'Grace Design m908 Surround Monitor Controller: 24-Channel Immersive Room Calibration',
  'Trinnov Audio D-MON: Acoustic Room Optimization in Asymmetric Post-Production Suites',
  'Mellanox Spectrum SN4000 Switches: 100GbE Non-Blocking Fabrics for Media Ingest',
  'Cisco Catalyst 9600 Enterprise Switches: Core Backbone Routing Across Studio Lots',
  'Arista 7280R3 Universal Leaf: Ultra-Deep Buffers for Burst-Heavy VFX Render Traffic',
  'Fortinet FortiGate 4000F: High-Throughput Hardware Encryption for MPAA Compliance',
  'Palo Alto Networks PA-5400: Zero-Trust Security Architectures for Remote Editorial',
  'YubiKey 5 FIPS Hardware Keys: Two-Factor Authentication Safeguards for Studio Clouds',
  'Air-Gapped Fiber Optic SAN Fabrics: Physical Isolation for Unreleased Blockbuster IP',
  'RAID 6 vs ZFS RAID-Z2: Rebuild Times and Bit Rot Prevention on 24TB Hard Drives',
  'Samsung 990 PRO NVMe Drives: Sustained Write Speeds Under Heavy Continuous DIT Loads',
  'Micron 9400 Enterprise NVMe: High-Endurance PCIe 4.0 Storage for Render Farms',
  'Kioxia CD8 Series PCIe 5.0 SSDs: Testing 14 GB/s Read Speeds in 8K Post Workstations',
  'Western Digital Ultrastar DC HC580 24TB: High-Density Helium Storage for Nearline Archives',
  'Seagate Exos Mozaic 3+ 30TB HAMR: Heat-Assisted Magnetic Recording Studio Reliability',
  'OWC ThunderBay 8 RAID: Thunderbolt 4 Field DIT Storage Configurations',
  'G-Technology ArmorATD: Ruggedized Field Storage for Brutal Location Shoots',
  'SanDisk Professional PRO-BLADE: Modular High-Speed NVMe Workflow Ecosystem',
  'Sony TOUGH CFexpress Type B: Extreme Shock and Temperature Resistance in the Field',
  'Angelbird AV PRO CFexpress Type A: High-Sustained Write Rates for Sony 8K Cameras',
  'ProGrade Digital PG05.6 Dual-Slot Readers: Thermal Throttling Prevention during Offload',
  'RED PRO CFexpress 2TB: Official Proprietary Certified Media for V-Raptor Bodies',
  'ARRI Codex Compact Drive 2TB: ARRIRAW Uncompressed Ingest Speeds on Alexa 35',
  'Sony AXS-A1TS66 AXS Memory Cards: 6.6 Gbps Throughput for Venice 2 8.6K Raw',
  'Anton Bauer Titon Micro Lithium-Ion Batteries: Flight-Safe Power for Rigged Cameras',
  'Core SWX Hypercore NEO 9: High-Draw Current Capabilities for Modern Cinema Bodies',
  'Bebob V-Mount Micro Batteries: Hot-Swap Buffering on Long High-Speed Takes',
  'Hawk-Woods Real-Time Battery Telemetry: Monitoring Remaining Watt-Hours over Bluetooth',
  'EcoFlow Delta Pro Portable Power Stations: Silent Mobile Power for Remote Set Lighting',
  'Jackery Explorer 3000 Pro: Clean Sine Wave Inverters for Sensitive Sound Gear',
  'Goal Zero Yeti PRO 4000: Industrial Battery Units for Commercial Production Sprinters',
  'Anker SOLIX F3800: Expanding Mobile Power Arrays on 3-Week Wilderness Shoots',
  'Aputure Electro Storm CS15: 1,500W Full-Color Point Source Fixtures on Stage Grids',
  'Nanlux Evoke 2400B: 2,400W Bi-Color LED Spotlights Replacing 4K HMI Fresnels',
  'ARRI Skypanel Pro: Wireless CRMX Mesh Control on Massive Rigging Grids',
  'Kino Flo Celeb 850: Soft LED Key Lighting with Precision Color Temperature Curves',
  'Astera Titan Tubes: Pixel-Addressable Wireless Tubes in In-Camera VFX Sets',
  'Quasar Science Rainbow 2: Linear LED Tubes with Built-In Wireless Art-Net Support',
  'Litepanels Gemini 2x1 Hard: Punchy Dynamic Beam Angles for Direct Sun Simulation',
  'Chauvet Professional Maverick Storm: IP65 Rated Moving Heads for Rain Stages',
  'Robe MegaPointe Automated Fixtures: High-Speed Spot and Beam Effects for Action Rigs',
  'Claypaky Sharpy Plus: Extreme Long-Throw Searchlight Simulation in Sci-Fi Sets',
  'ETC Source Four LED Series 3: Lustr X8 Color System for Studio Theater Sets',
  'Matthews Studio Equipment MAX Menace Arm: Safe Overhead Camera and Light Rigging',
  'Modern Studio Equipment Dana Dolly: Precision Portable Slider Systems on Track',
  'Ronford-Baker Heavy-Duty Fluid Heads: Counterbalance Engineering for 50-Pound Builds',
  'O\'Connor Ultimate 2575D Fluid Head: The Industry Gold Standard for Feature Motion',
  'Cartoni Master 65: Extreme Payload Fluid Heads for Heavy Anamorphic Zoom Packages',
  'Sachtler Cine 150: Carbon Fiber Tripod Legs with Heavy-Duty Spreader Systems',
  'EasyRig Vario 5 with Stabil: Relieving Operator Spinal Strain on 14-Hour Shoots',
  'Flowcine Black Arm: Complete 3-Axis Dampening for Chase Vehicle Rigging',
  'Tilta Armor Man 3: Exoskeleton Support for Heavy Gimbal Builds on Long Takes',
  'Ready Rig GS ProArm: Distributing Camera Weight to Operator Hips and Core',
  'Inovativ Voyager EVO Cart: High-End Aerospace Aluminum Mobile Workstations for DITs',
  'Magliner Senior Film Cart: Modular Shelving and Steadicam Bumper Accessories',
  'Pelican Air 1615 Travel Cases: Lightweight Honeycomb Polymer Protection for Lenses',
  'Cinema Server Virtualization: Hyperconverged Infrastructure for Visual Effects',
  'The Chief Technical Officer Role: Architecting Studio Infrastructure for 2030'
];

const techFullStories = create100CategoryStories(
  'tech',
  'Technology',
  techThemes,
  ['ARRI Alexa 35', 'Pure Storage', 'RTX 6000 Ada', 'DaVinci Resolve', 'OpenUSD'],
  title => `The development and industry adoption of ${title.toLowerCase()} showcases how physical hardware, high-speed storage fabrics, and optical engineering power modern motion picture production.`,
  title => `Under the hood, implementing ${title.toLowerCase()} requires meticulous thermal engineering, high-throughput network topologies, and calibrated color workflows to eliminate operational friction.`,
  title => `Studio technical directors note that investments in ${title.toLowerCase()} yield measurable reductions in turnaround times, safeguarding production budgets on high-stakes global releases.`
);

fs.writeFileSync(path.join(targetDir, 'tech.ts'), buildCategoryFile('tech', 'Technology', techFullStories), 'utf8');
console.log(`Generated ${techFullStories.length} Technology articles in tech.ts`);
